services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mmhow
      POSTGRES_USER: mmhow
      POSTGRES_PASSWORD: mmhow
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
