import type { Config } from 'tailwindcss'
import typography from '@tailwindcss/typography'

/** Modern FinTech theme — trust blue + action emerald (Stripe/Wise-inspired) */
const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        /* Core FinTech tokens */
        primary: '#2563EB',
        'on-primary': '#FFFFFF',
        accent: '#10B981',
        'on-accent': '#FFFFFF',
        background: '#F8FAFC',
        surface: '#F8FAFC',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F8FAFC',
        'surface-container': '#FFFFFF',
        'surface-container-high': '#F1F5F9',
        'surface-container-highest': '#E2E8F0',
        'on-surface': '#1E293B',
        'on-surface-variant': '#64748B',
        'on-background': '#1E293B',
        outline: '#E2E8F0',
        'outline-variant': '#E2E8F0',
        /* Legacy aliases mapped to FinTech palette */
        'surface-tint': '#1D4ED8',
        'primary-container': '#DBEAFE',
        'on-primary-container': '#1E3A8A',
        'primary-fixed': '#EFF6FF',
        'primary-fixed-dim': '#BFDBFE',
        'on-primary-fixed': '#1E3A8A',
        'on-primary-fixed-variant': '#1D4ED8',
        secondary: '#2563EB',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#EFF6FF',
        'on-secondary-container': '#1E40AF',
        'secondary-fixed': '#EFF6FF',
        'secondary-fixed-dim': '#DBEAFE',
        'on-secondary-fixed': '#1E3A8A',
        'on-secondary-fixed-variant': '#1D4ED8',
        tertiary: '#94A3B8',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': '#F1F5F9',
        'on-tertiary-container': '#475569',
        'tertiary-fixed': '#F8FAFC',
        'tertiary-fixed-dim': '#E2E8F0',
        'on-tertiary-fixed': '#0F172A',
        'on-tertiary-fixed-variant': '#64748B',
        'surface-variant': '#F1F5F9',
        'surface-dim': '#E2E8F0',
        'inverse-surface': '#0F172A',
        'inverse-on-surface': '#F8FAFC',
        'inverse-primary': '#93C5FD',
        'accent-muted': '#ECFDF5',
        error: '#DC2626',
        'on-error': '#FFFFFF',
        'error-container': '#FEE2E2',
        'on-error-container': '#991B1B',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.625rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'ad-clearance': '48px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        base: '8px',
        'stack-lg': '64px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Verdana', 'Geneva', '"DejaVu Sans"', 'sans-serif'],
        'body-lg': ['Verdana', 'Geneva', '"DejaVu Sans"', 'sans-serif'],
        'body-md': ['Verdana', 'Geneva', '"DejaVu Sans"', 'sans-serif'],
        'headline-md': ['Verdana', 'Geneva', '"DejaVu Sans"', 'sans-serif'],
        'label-md': ['Verdana', 'Geneva', '"DejaVu Sans"', 'sans-serif'],
        'display-lg': ['Verdana', 'Geneva', '"DejaVu Sans"', 'sans-serif'],
        'headline-lg': ['Verdana', 'Geneva', '"DejaVu Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      backgroundImage: {
        'hero-subtle': 'linear-gradient(180deg, #F8FAFC 0%, #FFFFFF 100%)',
      },
      boxShadow: {
        card: '0 1px 3px 0 rgb(226 232 240 / 0.4)',
        'card-hover': '0 4px 12px 0 rgb(226 232 240 / 0.5)',
        'cta-emerald': '0 4px 14px 0 rgb(16 185 129 / 0.2)',
      },
    },
  },
  plugins: [typography],
}

export default config
