import type { Config } from 'tailwindcss'
import typography from '@tailwindcss/typography'

/** Prosperity theme — growth green + gold accents for "how to make money" */
const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#0d9488',
        'on-error-container': '#7f1d1d',
        'tertiary-fixed-dim': '#d6d3d1',
        'on-tertiary-fixed-variant': '#44403c',
        'secondary-fixed-dim': '#fcd34d',
        'surface-variant': '#d1fae5',
        'tertiary-container': '#78716c',
        'on-tertiary-container': '#fafaf9',
        'primary-fixed': '#ccfbf1',
        'on-secondary-fixed-variant': '#78350f',
        background: '#fafaf7',
        'on-surface': '#1c1917',
        'on-surface-variant': '#57534e',
        'secondary-fixed': '#fef3c7',
        'primary-fixed-dim': '#99f6e4',
        'outline-variant': '#d6d3d1',
        surface: '#fafaf7',
        'on-tertiary': '#ffffff',
        'primary-container': '#047857',
        'tertiary': '#78716c',
        'inverse-on-surface': '#ecfdf5',
        'surface-bright': '#ffffff',
        'inverse-primary': '#6ee7b7',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#14532d',
        'error-container': '#fee2e2',
        'on-tertiary-fixed': '#1c1917',
        'surface-container-high': '#d1fae5',
        'on-error': '#ffffff',
        'on-primary-container': '#ecfdf5',
        'on-primary-fixed-variant': '#065f46',
        'on-background': '#1c1917',
        outline: '#a8a29e',
        'on-secondary-fixed': '#451a03',
        secondary: '#b45309',
        'surface-container': '#ecfdf5',
        'on-primary-fixed': '#022c22',
        primary: '#059669',
        'surface-dim': '#e7e5e4',
        'tertiary-fixed': '#f5f5f4',
        'on-secondary-container': '#78350f',
        'on-primary': '#ffffff',
        'secondary-container': '#fef9c3',
        error: '#dc2626',
        'surface-container-highest': '#a7f3d0',
        'surface-container-low': '#f0fdf4',
        'on-secondary': '#ffffff',
        accent: '#d97706',
        'on-accent': '#ffffff',
        'accent-muted': '#fef3c7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.375rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'ad-clearance': '48px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        base: '8px',
        'stack-lg': '64px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'headline-lg-mobile': ['var(--font-source-serif)', 'serif'],
        'body-lg': ['var(--font-source-sans)', 'sans-serif'],
        'body-md': ['var(--font-source-sans)', 'sans-serif'],
        'headline-md': ['var(--font-source-serif)', 'serif'],
        'label-md': ['var(--font-source-sans)', 'sans-serif'],
        'display-lg': ['var(--font-source-serif)', 'serif'],
        'headline-lg': ['var(--font-source-serif)', 'serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      backgroundImage: {
        'money-gradient': 'linear-gradient(135deg, #ecfdf5 0%, #fef9c3 50%, #fafaf7 100%)',
        'hero-glow': 'radial-gradient(ellipse 80% 60% at 70% 40%, rgba(5, 150, 105, 0.12), transparent)',
      },
    },
  },
  plugins: [typography],
}

export default config
